.\"                                      EMACS: -*- nroff -*-

.TH DEBIAN-UMGMT 1 "February 10, 2015"

.SH NAME
debian-umgmt \- small TUI tool to manage users on Debian

.SH SYNOPSIS
.B debian-umgmt [ -h | -v ]
.br

.SH DESCRIPTION
This manual page documents briefly the
.B debian-umgmt
command.
.PP


\fBdebian-umgmt\fP is an interactive menu-driven program that can be used 
to list, add and remove user accounts via a newt-based text user interface 
on Debian. Modifiying group memberships of users is also possible. 

.SH OPTIONS
The program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.

.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.

.SH SEE ALSO
.BR adduser (8),
.BR deluser (8), 
.BR usermod (8).
.br

.SH AUTHOR
\fBdebian-umgmt\fP and this manual page were written by Dennis Thekumthala 
<flakeshake@users.noreply.github.com>, for the Debian GNU/Linux system.
